### PR TITLE
Fix extra parenthesis.

### PR DESCRIPTION
**Pull request by theherk**
This makes the plugin work, but using `q` as the default close seems to me not to work. I haven't looked further into it yet.

### CODE REVIEW

**Review by FredeEB — COMMENTED** [review]
What situation did you encounter this error in? `fd` should always be an integer, otherwise there's something else wrong

**Comment by FredeEB** [comment]
Ah, okay. I see what happened here. I'll merge the commit with the missing paren, and fix the fd being nil error

**Comment by FredeEB** [comment]
@theherk I just refactored the session management part of tardis, removing some unnecessary logic. It should work better now. Let met know if you encounter any further issues.

Thanks again

**Comment by theherk** [comment]
It does seem to be working great. Nice work.

**Pull request closed without merging**
